import type { AgentConfig } from './engineering'

export const modelCapabilityLabels = {
  'aa-intelligence': '综合推理 · AA Intelligence Index',
  'aa-coding': '终端编程 · AA Terminal-Bench 4.0',
  webdev: 'Web 开发 · 综合',
  frontend: '前端开发 · HTML / React',
  fullstack: '全栈 Web 开发',
  coding: '代码理解与生成',
  text: '综合问答与分析',
} as const
export type ModelCapability = keyof typeof modelCapabilityLabels
export type ModelSelectionPolicy = 'quality' | 'pareto'
export interface ModelRecommendationOptions {
  categories?: Record<string, ModelCapability>
  policy?: ModelSelectionPolicy
}
export function defaultModelCapability(agent: Pick<AgentConfig, 'name' | 'role' | 'instructions'>): ModelCapability {
  if (agent.role === 'designer' || /前端|原型|界面|frontend|front-end|UI\/UX/i.test(agent.name)) return 'frontend'
  if (/全栈|fullstack|full-stack/i.test(agent.name)) return 'fullstack'
  if (agent.role === 'planner') return 'aa-intelligence'
  return 'aa-coding'
}
export interface ArenaScore {
  model: string
  rank: number
  score: number
  lower?: number
  upper?: number
  votes: number
  preliminary: boolean
  inputPrice?: number
  outputPrice?: number
}
export interface ModelEvidenceCandidate {
  displayName?: string
  query?: string
  matchNote?: string
  connectionId: string
  model: string
  match: 'exact' | 'unmatched' | 'ambiguous'
  score?: ArenaScore | AAScore
  /** Display-only references. Never use these scores for allocation or Pareto. */
  similar?: { score: ArenaScore | AAScore; url: string; note: string }[]
  pareto: 'frontier' | 'dominated' | 'unknown'
}
export interface ModelCapabilityEvidence {
  agentId?: string
  source?: 'arena' | 'aa'
  category: ModelCapability
  url: string
  fetchedAt: string
  updatedAt?: string
  status: 'fresh' | 'stale' | 'unavailable'
  note: string
  candidates: ModelEvidenceCandidate[]
}
export interface AAScore {
  model: string
  score: number
  metric: 'aa-intelligence' | 'aa-coding'
  url: string
  preliminary: boolean
  inputPrice?: number
  outputPrice?: number
  rank?: never
  votes?: never
  lower?: never
  upper?: never
}

/** Only public benchmark pages generated by the evidence collectors may open. */
export function isModelEvidenceUrl(value: unknown): value is string {
  if (typeof value !== 'string' || value.length > 2000) return false
  try {
    const url = new URL(value)
    if (url.href !== value || url.protocol !== 'https:' || url.username || url.password || url.port || url.search || url.hash) return false
    if (url.hostname === 'artificialanalysis.ai') return /^\/models(?:\/[a-z0-9][a-z0-9-]{0,180})?$/.test(url.pathname)
    return url.hostname === 'arena.ai' && ['/leaderboard/code', '/leaderboard/code/webdev/frontend', '/leaderboard/code/webdev/fullstack', '/leaderboard/text', '/leaderboard/text/coding'].includes(url.pathname)
  } catch { return false }
}
