const { _electron: electron } = require('playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const { join, resolve } = require('node:path')
const { startProvider } = require('./fixtures/engineering-provider.cjs')

async function main() {
  const output = resolve('output/playwright/novice')
  await fs.mkdir(output, { recursive: true })
  const profile = await fs.mkdtemp(join(output, 'profile-'))
  const parent = await fs.mkdtemp(join(output, 'projects-'))
  const provider = await startProvider()
  const env = { ...process.env, COPROJER_USER_DATA: profile }; delete env.ELECTRON_RUN_AS_NODE
  let desktop, page
  const errors = []
  const invoke = (method, ...args) => page.evaluate(({ method, args }) => window.desktop.engineering[method](...args), { method, args })
  const state = () => invoke('state')
  const project = async () => (await state()).projects[0]
  const waitFor = async (predicate, label) => { const start = Date.now(); while (Date.now() - start < 60000) { if (await predicate()) return; await new Promise(r => setTimeout(r, 120)) } throw new Error('Timed out: ' + label) }
  const idle = () => waitFor(async () => !(await project()).activity && !(await project()).designActivity, 'idle')
  async function launch() {
    desktop = await electron.launch({ args: ['.', '--disable-gpu'], env, timeout: 30000 })
    page = await desktop.firstWindow()
    page.on('pageerror', e => errors.push(e.message))
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.getByRole('heading', { name: '工作台', exact: true }).waitFor()
  }
  try {
    await launch()
    assert.deepEqual((await state()).agents.map(a => a.role).sort(), ['designer', 'developer', 'planner', 'reviewer'])
    assert.equal((await invoke('preflight', parent)).ready, true)
    await page.getByRole('button', { name: '创建项目', exact: true }).click()
    const create = page.getByRole('dialog', { name: '新建工程项目' })
    await create.getByPlaceholder('例如：个人记账').fill('保留中的项目草稿')
    await create.getByPlaceholder('描述要解决的问题，以及希望交付的软件。').fill('保存模型后继续创建。')
    await create.getByRole('button', { name: '先连接模型', exact: true }).click()
    const modelDialog = page.getByRole('dialog', { name: '新增模型' })
    await modelDialog.getByPlaceholder('例如：我的开发模型').fill('新手流程模型')
    await modelDialog.getByPlaceholder('https://your-service.example/v1').fill(provider.baseUrl)
    await modelDialog.getByPlaceholder('填写或选择模型 ID').fill('fixture')
    await modelDialog.getByRole('button', { name: '检查开发能力', exact: true }).click()
    await modelDialog.getByText('开发能力检查通过：工具调用、结果回传和 JSON 均可用。').waitFor()
    await modelDialog.getByRole('button', { name: '保存模型', exact: true }).click()
    await create.waitFor()
    assert.equal(await create.getByPlaceholder('例如：个人记账').inputValue(), '保留中的项目草稿')
    assert.equal(await create.getByPlaceholder('描述要解决的问题，以及希望交付的软件。').inputValue(), '保存模型后继续创建。')
    const model = (await state()).models[0]
    assert.equal(await create.locator('select').inputValue(), model.id)
    await create.getByRole('button', { name: '取消', exact: true }).click()
    assert.ok((await state()).agents.every(a => a.modelId === model.id && a.skillIds.length))
    await page.getByRole('button', { name: '智能体', exact: true }).click()
    await desktop.evaluate(({ dialog }, folder) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [folder] }) }, resolve('docs/skills/local-verification'))
    await page.getByRole('button', { name: '导入本地技能', exact: true }).click()
    await waitFor(async () => (await state()).skills.some(s => s.id === 'local-verification'), 'skill imported')
    await page.locator('.eng-agent-card').filter({ hasText: '验证智能体' }).getByRole('button', { name: '配置', exact: true }).click()
    const reviewerDialog = page.getByRole('dialog', { name: '配置智能体' })
    await reviewerDialog.getByRole('checkbox', { name: /业务边界检查/ }).check()
    await reviewerDialog.getByRole('button', { name: '保存智能体', exact: true }).click()
    for (const protocol of ['chat', 'responses', 'anthropic']) assert.match(await invoke('testCapabilities', { ...model, protocol, apiKey: '' }), /开发能力检查通过/)
    const pid = await invoke('createProject', { name: '新手流程', parent, brief: '做一个可在本机运行的记账应用。', modelId: model.id })
    const make = (title, dependencies = []) => ({ title, module: '账目', description: '记录收入支出并检查金额', criteria: ['金额计算正确'], scope: 'discussion', dependencies, developerId: 'developer', reviewerId: 'reviewer' })
    assert.equal((await project()).features.length, 0)
    assert.ok(!(await project()).requirementsDocument)
    await assert.rejects(invoke('preparePrd', pid), /先确定并验收/)
    await page.getByRole('button', { name: '需求与功能图', exact: true }).click()
    await page.getByRole('textbox', { name: '我的设计意见', exact: true }).waitFor()
    for (const [width, height] of [[1280, 840], [860, 600]]) {
      await desktop.evaluate(({ BrowserWindow }, size) => BrowserWindow.getAllWindows()[0].setSize(...size), [width, height])
      await page.screenshot({ path: join(output, 'design-opinion-' + width + '-light.png'), animations: 'disabled', scale: 'css' })
    }
    await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1280, 840))
    await page.getByRole('textbox', { name: '我的设计意见', exact: true }).fill('手机优先，浅色简洁，首页突出收支与结余。')
    await page.getByRole('button', { name: '提交设计意见', exact: true }).click()
    await idle()
    await waitFor(async () => (await project()).prototypeBriefs?.['']?.status === 'review', 'automatic prototype review')
    const firstPrototype = (await project()).prototypes[0].id
    await assert.rejects(invoke('preparePrd', pid), /先确定并验收/)
    await page.frameLocator('iframe[title="原型实时预览"]').getByRole('heading', { name: '个人记账', exact: true }).waitFor()
    await page.screenshot({ path: join(output, 'prototype-review-1280-light.png'), animations: 'disabled', scale: 'css' })
    await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(860, 600))
    await page.screenshot({ path: join(output, 'prototype-review-860-light.png'), animations: 'disabled', scale: 'css' })
    assert.ok((await page.locator('iframe[title="原型实时预览"]').boundingBox()).height > 180)
    await page.getByRole('button', { name: '提出修改意见', exact: true }).click()
    await page.getByRole('textbox', { name: '我的设计意见', exact: true }).fill('金额输入更突出，保留第一版的整体布局。')
    await page.getByRole('button', { name: '提交设计意见', exact: true }).click()
    await idle()
    await waitFor(async () => (await project()).prototypes.length === 2, 'automatic prototype revision')
    await page.getByLabel('原型版本', { exact: true }).selectOption(firstPrototype)
    await page.getByRole('button', { name: '验收此原型', exact: true }).click()
    await waitFor(async () => (await project()).prototypeBriefs[''].status === 'accepted', 'prototype accepted')
    await idle()
    assert.equal((await project()).prd.status, 'review')
    assert.equal((await project()).prd.sources[0].prototypeId, firstPrototype)
    const first = (await project()).features.find(f => f.title === '记录收支').id
    const secondFeature = (await project()).features.find(f => f.title === '查看结余')
    const second = secondFeature.id
    await invoke('saveFeature', pid, second, { ...secondFeature, dependencies: [first] })
    // A failed/missing original read must preserve the accepted prototype and last PRD.
    const previousDocument = (await project()).requirementsDocument
    provider.control.skipPrdRead = true
    await assert.rejects(invoke('preparePrd', pid), /未完整读取已确认原型/)
    provider.control.skipPrdRead = false
    assert.equal((await project()).prd.status, 'error')
    assert.equal((await project()).requirementsDocument, previousDocument)
    assert.equal((await project()).prototypeBriefs[''].status, 'accepted')
    await assert.rejects(invoke('confirmRequirements', pid, first), /PRD/)
    // An interrupted retry remains retryable; no already-approved design is discarded.
    provider.control.hold = true
    const interruptedPrd = invoke('preparePrd', pid).then(() => '', e => String(e))
    await waitFor(() => provider.control.held.length > 0, 'PRD held')
    await invoke('stop', pid)
    assert.match(await interruptedPrd, /停止|中断|abort/i)
    provider.release()
    await idle()
    assert.equal((await project()).prototypeBriefs[''].status, 'accepted')
    await page.getByRole('button', { name: '根据已确认原型生成 PRD', exact: true }).click()
    await idle()
    await waitFor(async () => (await project()).prd.status === 'review', 'PRD retry')
    assert.equal((await project()).prototypeBriefs[''].status, 'accepted')
    for (const [width, height] of [[1280, 840], [860, 600]]) {
      await desktop.evaluate(({ BrowserWindow }, size) => BrowserWindow.getAllWindows()[0].setSize(...size), [width, height])
      await page.screenshot({ path: join(output, 'prd-ready-' + width + '-light.png'), animations: 'disabled', scale: 'css' })
    }
    await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1280, 840))
    await page.getByRole('button', { name: '确认完整需求', exact: true }).click()
    await page.screenshot({ path: join(output, 'prd-review-1280-light.png'), animations: 'disabled', scale: 'css' })
    await page.getByRole('button', { name: '确认需求并准备方案', exact: true }).click()
    await idle()
    await waitFor(async () => (await project()).features.every(f => f.plan && f.stage === 'solution'), 'prepared plans')
    let p = await project()
    assert.equal(p.prd.status, 'confirmed')
    assert.ok(p.features.every(f => f.prototypeId === firstPrototype && f.baselineId === p.requirementsBaseline.id))
    assert.ok(p.context.find(c => c.id === p.requirementsBaseline.id).content.includes('prototype:' + firstPrototype))
    await page.getByRole('button', { name: '工作台', exact: true }).click()
    await page.getByRole('button', { name: '审阅方案并开始', exact: true }).click()
    const review = page.getByRole('dialog', { name: '审阅方案并开始' })
    await review.waitFor()
    const versions = p.features.map(f => f.revision)
    await invoke('savePlan', pid, first, p.features[0].plan + ' 补充启动检查。', ['实现', '测试'])
    await assert.rejects(invoke('confirmPlansAndStart', pid, [first, second], versions), /方案已有更新/)
    await review.getByRole('button', { name: '取消', exact: true }).click()
    await page.getByRole('button', { name: '审阅方案并开始', exact: true }).click()
    await review.waitFor()
    await review.locator('summary').first().click()
    for (const [width, height] of [[1280, 840], [860, 600]]) {
      await desktop.evaluate(({ BrowserWindow }, size) => BrowserWindow.getAllWindows()[0].setSize(...size), [width, height])
      await page.screenshot({ path: join(output, 'plan-review-' + width + '-light.png'), animations: 'disabled', scale: 'css' })
      assert.equal(await review.evaluate(el => el.scrollWidth > el.clientWidth), false)
    }
    await review.getByRole('button', { name: '确认方案并开始', exact: true }).focus()
    assert.equal(await review.getByRole('button', { name: '确认方案并开始', exact: true }).evaluate(el => el === document.activeElement), true)
    await page.getByRole('button', { name: '确认方案并开始', exact: true }).click()
    await review.waitFor({ state: 'hidden' })
    await waitFor(async () => (await project()).features.find(f => f.id === first).stage === 'acceptance', 'first acceptance')
    await idle()
    assert.equal(provider.control.developments, 1)
    assert.equal((await project()).features.find(f => f.id === first).prototypeResult?.passed, true)
    const actualPage = await fs.readFile(join((await project()).root, 'index.html'), 'utf8')
    const acceptedHtml = (await project()).prototypes.find(p => p.id === firstPrototype).html
    assert.equal(actualPage.match(/<style>[\s\S]*?<\/style>/)[0], acceptedHtml.match(/<style>[\s\S]*?<\/style>/)[0])
    assert.match(actualPage, /data-prototype-layout="approved-ledger"/)
    assert.ok(actualPage.includes('localStorage.setItem') && !acceptedHtml.includes('localStorage.setItem'))
    assert.equal((await project()).features.find(f => f.id === second).stage, 'ready')
    await page.getByRole('button', { name: '查看验收', exact: true }).first().click()
    await page.getByRole('button', { name: '验收通过并继续', exact: true }).click()
    await waitFor(async () => (await project()).features.find(f => f.id === second).stage === 'acceptance', 'second acceptance')
    await idle()
    assert.equal(provider.control.developments, 2)
    await invoke('acceptAndContinue', pid, second)
    assert.equal((await project()).executionPlan.status, 'completed')
    const runs = (await project()).agentRuns
    for (const role of ['planner', 'designer', 'developer', 'reviewer']) assert.ok(runs.some(r => r.role === role && r.skills.length && r.contextCharacters > 0))
    assert.ok(runs.some(r => r.role === 'reviewer' && r.skills.some(s => s.id === 'local-verification' && s.version === '1.0.0' && s.hash.length === 64)))
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '工作台', exact: true }).click()
    for (const [width, height] of [[1280, 840], [860, 600]]) {
      await desktop.evaluate(({ BrowserWindow }, size) => BrowserWindow.getAllWindows()[0].setSize(...size), [width, height])
      for (const theme of ['light', 'dark']) {
        await page.evaluate(theme => { document.documentElement.dataset.theme = theme }, theme)
        await page.screenshot({ path: join(output, 'workflow-' + width + '-' + theme + '.png'), animations: 'disabled', scale: 'css' })
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
      }
    }
    await page.getByRole('button', { name: '智能体', exact: true }).click()
    assert.equal(await page.locator('.eng-agent-card').count(), 4)
    await page.locator('.eng-agent-card').filter({ hasText: '任务规划智能体' }).getByRole('button', { name: '配置', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '配置智能体' })
    assert.equal(await dialog.getByRole('checkbox', { name: '修改文件', exact: true }).isDisabled(), true)
    assert.equal(await dialog.locator('.eng-skill-options input:checked').count(), 1)
    await dialog.locator('.eng-skill-options').scrollIntoViewIfNeeded()
    await page.screenshot({ path: join(output, 'skills-compact-dark.png'), animations: 'disabled', scale: 'css' })
    await dialog.getByRole('button', { name: '取消', exact: true }).click()
    await invoke('saveContext', pid, null, '可归档的工程说明', 'ARCHIVE_TEST_MARKER')
    const note = (await project()).context.find(c => c.title === '可归档的工程说明')
    await page.getByRole('button', { name: '共享上下文', exact: true }).click()
    await page.locator('.eng-context-entry').filter({ hasText: note.title }).click()
    await page.getByRole('button', { name: '归档', exact: true }).click()
    await waitFor(async () => (await project()).context.find(c => c.id === note.id).status === 'archived', 'archived')
    await invoke('saveContext', pid, note.id, note.title, 'UPDATED_ARCHIVE_MARKER')
    assert.equal((await project()).context.find(c => c.id === note.id).status, 'archived')
    assert.equal((await project()).context.find(c => c.id === note.id).revision, 2)
    await page.getByRole('button', { name: '恢复使用', exact: true }).click()
    await waitFor(async () => (await project()).context.find(c => c.id === note.id).status === 'active', 'restored')
    await assert.rejects(invoke('archiveContext', pid, (await project()).requirementsBaseline.id, true), /不能归档/)
    await page.locator('.eng-context-run summary').click()
    await page.screenshot({ path: join(output, 'context-compact-dark.png'), animations: 'disabled', scale: 'css' })
    await desktop.close(); desktop = null
    // Simulate an old profile: migration must preserve customized roles and finished work.
    const diskPath = join(profile, 'engineering-v1.json'), disk = JSON.parse(await fs.readFile(diskPath, 'utf8'))
    // Simulate a process exit during PRD generation in an independent project.
    const interrupted = structuredClone(disk.projects[0])
    interrupted.id = 'interrupted-prd'
    interrupted.root = await fs.mkdtemp(join(parent, 'interrupted-prd-'))
    interrupted.activity = '根据已确认原型生成 PRD'
    interrupted.prd.status = 'generating'
    disk.projects.push(interrupted)
    disk.agents = disk.agents.filter(a => ['developer', 'reviewer'].includes(a.role))
    disk.agents[0].instructions = 'USER_CUSTOMIZATION_MARKER'
    for (const a of disk.agents) delete a.skillIds
    await fs.writeFile(diskPath, JSON.stringify(disk))
    await launch()
    assert.equal((await state()).agents.length, 4)
    assert.ok((await state()).agents.some(a => a.instructions === 'USER_CUSTOMIZATION_MARKER'))
    assert.equal((await project()).executionPlan.status, 'completed')
    assert.ok((await project()).features.every(f => f.stage === 'done'))
    const recovered = (await state()).projects.find(p => p.id === interrupted.id)
    assert.equal(recovered.prd.status, 'error')
    assert.equal(recovered.activity, null)
    assert.equal(recovered.prototypeBriefs[''].status, 'accepted')
    assert.equal(recovered.requirementsDocument, interrupted.requirementsDocument)
    await invoke('preparePrd', interrupted.id)
    assert.equal((await state()).projects.find(p => p.id === interrupted.id).prd.status, 'review')
    const batchId = await invoke('createProject', { name: '跨批次方案', parent, brief: '验证 21 项方案准备与成功复用。', modelId: model.id })
    const batchFeatureIds = []
    for (let index = 1; index <= 21; index++) {
      const id = await invoke('saveFeature', batchId, null, make('批量功能 ' + index))
      batchFeatureIds.push(id)
    }
    await invoke('submitPrototypePreferences', batchId, '统一简洁列表，清楚展示各项功能。')
    await waitFor(async () => !(await state()).projects.find(p => p.id === batchId).designActivity, 'batch prototype')
    await invoke('selectPrototype', batchId, (await state()).projects.find(p => p.id === batchId).prototypes.at(-1).id)
    await assert.rejects(invoke('confirmRequirements', batchId, batchFeatureIds[0]), /PRD/)
    await invoke('preparePrd', batchId)
    for (const id of batchFeatureIds) await invoke('confirmRequirements', batchId, id)
    const prepared = await invoke('preparePlans', batchId)
    assert.equal(prepared.length, 21)
    assert.ok(prepared.every(r => r.success))
    assert.deepEqual(await invoke('preparePlans', batchId), [])
    assert.deepEqual(errors, [])
    assert.deepEqual(provider.control.errors, [])
    console.log('PASS: prototype-first flow without predefined features, automatic PRD with full source reads, PRD failure/stop/restart recovery, first-run draft preservation, four-role migration, skills, three-protocol capabilities, pinned prototype reused in real source, 21-plan preparation, stale approval guard, serial delivery and acceptance, context archive/restore, both layouts/themes')
  } finally { if (desktop) await desktop.close(); await provider.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
