const assert=require('node:assert/strict'),fs=require('node:fs/promises'),{join,resolve}=require('node:path')
const {_electron:electron}=require('playwright'),{aaHtml}=require('./fixtures/aa.cjs'),{allocationFixture,categories}=require('./fixtures/arena.cjs')
async function main(){
  const output=resolve('output/playwright/reasoning');await fs.mkdir(output,{recursive:true})
  const profile=await fs.mkdtemp(join(output,'profile-')),env={...process.env,COPROJER_USER_DATA:profile},errors=[],captures=[]
  delete env.ELECTRON_RUN_AS_NODE
  let app,page
  const invoke=(method,...args)=>page.evaluate(({method,args})=>window.desktop.engineering[method](...args),{method,args}),state=()=>invoke('state')
  async function launch(){
    app=await electron.launch({args:['.','--disable-gpu'],env});page=await app.firstWindow();page.setDefaultTimeout(12000)
    page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'reduce'})
    await page.getByRole('heading',{name:'项目管理',exact:true}).waitFor()
    await app.evaluate((_,fixtures)=>{
      globalThis.__reasoningFetches=[];globalThis.__offlineAA=false;globalThis.__modelPayloads=[]
      globalThis.fetch=async(url,init={})=>{
        const u=String(url);globalThis.__reasoningFetches.push(u)
        if(u.startsWith('https://artificialanalysis.ai/'))return new Response(globalThis.__offlineAA?'offline':fixtures.aa,{status:globalThis.__offlineAA?503:200,headers:{'content-type':'text/html'}})
        if(u.startsWith('https://arena.ai/'))return new Response(fixtures.arena[new URL(u).pathname],{headers:{'content-type':'text/html'}})
        if(u.startsWith('https://open.bigmodel.cn/')){
          const body=JSON.parse(init.body),input=JSON.parse(body.messages.at(-1).content);globalThis.__modelPayloads.push(body)
          const choices=input.agents.map(a=>({agentId:a.id,modelId:input.constraints.find(c=>c.agentId===a.id).allowedModelIds[0]}))
          return new Response(JSON.stringify({model:body.model,choices:[{message:{content:JSON.stringify({choices})}}]}),{headers:{'content-type':'application/json'}})
        }
        throw Error('Blocked unmocked request: '+new URL(u).hostname)
      }
    },{aa:aaHtml(),arena:Object.fromEntries(Object.keys(categories).map(p=>[p,allocationFixture('https://arena.ai'+p)]))})
  }
  async function capture(name,width,height,theme='light',maximized=false){
    if(maximized)({width,height}=await app.evaluate(({BrowserWindow,screen})=>{const w=BrowserWindow.getAllWindows()[0];w.maximize();return screen.getDisplayMatching(w.getBounds()).workAreaSize}))
    else await app.evaluate(({BrowserWindow},{width,height})=>{const w=BrowserWindow.getAllWindows()[0];w.unmaximize();w.setSize(width,height)},{width,height})
    await page.waitForFunction(({width,height})=>innerWidth===width&&innerHeight===height,{width,height})
    await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme)
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'workbench overflow')
    const dialog=page.getByRole('dialog');if(await dialog.count())assert.ok(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'dialog overflow')
    if(maximized && name==='01-agent-settings')await dialog.getByText('智能体名称',{exact:true}).scrollIntoViewIfNeeded()
    const file=join(output,name+'-'+theme+'-'+width+'x'+height+'.png');await page.screenshot({path:file});captures.push({file,width,height,theme,maximized})
  }
  try{
    await launch()
    const configs=[{id:'glm',model:'glm-5.3',baseUrl:'https://open.bigmodel.cn/api/coding/paas/v4'},{id:'kimi',model:'kimi-k3',baseUrl:'https://test.cn-beijing.maas.aliyuncs.com/compatible-mode/v1'},{id:'qwen',model:'qwen3.7-flash',baseUrl:'https://test.cn-beijing.maas.aliyuncs.com/compatible-mode/v1'}]
    for(const config of configs)await invoke('saveModel',{...config,protocol:'chat',apiKey:'isolated-fixture-key'})
    await invoke('setDefaultAssistantModel','glm')
    const dev=(await state()).agents.find(a=>a.id==='developer')
    await invoke('saveAgent',{...dev,id:'qwen-instance',name:'预算实例',modelId:'qwen',skillIds:[]})
    await page.getByRole('button',{name:'智能体',exact:true}).click()
    const card=name=>page.locator('.eng-agent-card').filter({hasText:name})
    for(const [w,h]of [[1280,840],[860,600]]){await capture('agent-cards',w,h);assert.ok(await page.locator('.eng-agent-card').evaluateAll(cards=>cards.every(e=>e.scrollWidth<=e.clientWidth+1)),'long model labels must fit the agent cards')}
    await card('开发智能体').getByRole('button',{name:'配置',exact:true}).click()
    let dialog=page.getByRole('dialog',{name:'配置智能体',exact:true})
    assert.equal(await dialog.getByLabel('推理强度',{exact:true}).inputValue(),'max')
    assert.ok(await dialog.getByLabel('是否推理',{exact:true}).isDisabled())
    await dialog.getByLabel('推理强度',{exact:true}).selectOption('low')
    await dialog.getByLabel('使用模型',{exact:true}).selectOption('kimi')
    assert.equal(await dialog.getByLabel('推理强度',{exact:true}).inputValue(),'low','compatible effort survives an explicit model change')
    await dialog.getByLabel('使用模型',{exact:true}).selectOption('qwen')
    assert.equal(await dialog.getByLabel('思考预算',{exact:true}).inputValue(),'','incompatible effort resets to the new model maximum budget')
    await dialog.getByLabel('使用模型',{exact:true}).selectOption('glm')
    assert.equal(await dialog.getByLabel('推理强度',{exact:true}).inputValue(),'max')
    await dialog.getByLabel('推理强度',{exact:true}).selectOption('low')
    await dialog.locator('.eng-reasoning-options').scrollIntoViewIfNeeded()
    for(const theme of ['light','dark'])for(const [w,h]of [[1280,840],[860,600]])await capture('agent-settings',w,h,theme)
    await capture('01-agent-settings',0,0,'light',true)
    await dialog.getByRole('button',{name:'保存智能体',exact:true}).click();await dialog.waitFor({state:'hidden'})
    assert.deepEqual((await state()).agents.find(a=>a.id==='developer').reasoning,{enabled:true,effort:'low'})
    assert.equal((await state()).agents.find(a=>a.id==='reviewer').reasoning,undefined)
    assert.match(await card('开发智能体').innerText(),/glm-5.3 · Low/)
    assert.match(await card('验证智能体').innerText(),/glm-5.3 · Max/)
    await card('预算实例').getByRole('button',{name:'配置',exact:true}).click();dialog=page.getByRole('dialog',{name:'配置智能体',exact:true})
    assert.equal(await dialog.getByLabel('思考预算',{exact:true}).inputValue(),'')
    await dialog.getByLabel('思考预算',{exact:true}).fill('4096')
    await dialog.getByLabel('是否推理',{exact:true}).selectOption('off');assert.ok(await dialog.getByLabel('思考预算',{exact:true}).isDisabled())
    await capture('budget-off',860,600)
    await dialog.getByRole('button',{name:'保存智能体',exact:true}).click();await dialog.waitFor({state:'hidden'})
    assert.deepEqual((await state()).agents.find(a=>a.id==='qwen-instance').reasoning,{enabled:false,budget:4096})
    await page.getByRole('button',{name:'模型配置助手',exact:true}).click()
    dialog=page.getByRole('dialog',{name:'模型配置助手',exact:true})
    const before=await state();await dialog.getByRole('button',{name:'一键推荐模型',exact:true}).click()
    await dialog.getByRole('heading',{name:/模型分配预览/}).waitFor()
    assert.deepEqual((await state()).agents,before.agents)
    const article=dialog.locator('.eng-model-plan article').filter({hasText:'开发智能体'})
    assert.match(await article.innerText(),/推荐：kimi-k3 · Low/)
    const evidence=dialog.locator('.eng-model-evidence details').filter({has:page.locator('summary',{hasText:'开发智能体'})})
    await evidence.locator('summary').click()
    assert.match(await evidence.innerText(),/查询：glm-5.3 \(low\)/)
    assert.match(await evidence.innerText(),/20.00%/)
    await evidence.scrollIntoViewIfNeeded()
    for(const theme of ['light','dark'])for(const [w,h]of [[1280,840],[860,600]])await capture('aa-evidence',w,h,theme)
    await capture('02-aa-evidence',0,0,'light',true)
    const firstFetch=await app.evaluate(()=>globalThis.__reasoningFetches.filter(u=>u==='https://artificialanalysis.ai/models').length)
    assert.equal(firstFetch,1)
    await dialog.getByRole('button',{name:'一键应用模型配置',exact:true}).click();await dialog.getByText(/已应用 \d+ 项模型变更/).waitFor()
    assert.deepEqual((await state()).agents.find(a=>a.id==='developer').reasoning,{enabled:true,effort:'low'})
    assert.equal((await state()).agents.find(a=>a.id==='developer').modelId,'kimi')
    assert.deepEqual((await state()).skills,before.skills)
    await app.evaluate(()=>{globalThis.__offlineAA=true})
    await dialog.getByRole('button',{name:'一键推荐模型',exact:true}).click();await dialog.getByRole('heading',{name:/模型分配预览 · 0 项变更/}).waitFor()
    assert.equal(await app.evaluate(()=>globalThis.__modelPayloads.length),1,'offline evidence must not call advisor')
    assert.equal(await app.evaluate(()=>globalThis.__reasoningFetches.filter(u=>u==='https://artificialanalysis.ai/models').length),2)
    const persisted=await state();await app.close();app=null;await launch()
    assert.deepEqual((await state()).agents,persisted.agents);assert.deepEqual((await state()).skills,persisted.skills)
    assert.deepEqual(errors,[])
    await fs.writeFile(join(output,'result.json'),JSON.stringify({passed:true,captures,checks:['instance isolation','highest default','immutable API ID','disabled forced-thinking switch','budget off persistence','AA effort-specific recommendation','offline preservation','restart persistence','light/dark 1280x840 and 860x600'],errors},null,2))
    console.log('PASS reasoning Electron: per-instance controls, correct model labels, AA evidence and apply, offline preservation, restart and four layouts; '+captures.length+' screenshots')
  }finally{await app?.close();await fs.rm(profile,{recursive:true,force:true})}
}
main().catch(e=>{console.error(e);process.exitCode=1})
