import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{todayStats,History,validDuration}from'./model';
type Mode='focus'|'short'|'long';type Settings={focus:number;short:number;long:number;sound:boolean;volume:number;theme:'light'|'dark'};type Snap={mode:Mode;left:number;completedInSet:number};
const defaults:Settings={focus:1500,short:300,long:900,sound:true,volume:70,theme:'light'};const labels={focus:'专注',short:'短休息',long:'长休息'};
function load<T>(k:string,d:T):T{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}}
function App(){const[settings,setSettings]=useState(()=>({...defaults,...load<Partial<Settings>>('settings',{})}));const snap=load<Snap|null>('timer-snapshot',null);const[mode,setMode]=useState<Mode>(snap?.mode||'focus'),[left,setLeft]=useState(snap?.left??settings.focus),[setCount,setSetCount]=useState(snap?.completedInSet||0),[running,setRunning]=useState(false),[deadline,setDeadline]=useState(0),[history,setHistory]=useState<History[]>(()=>load('history',[])),[tab,setTab]=useState('timer'),[notice,setNotice]=useState(snap?'已恢复上次计时，请点击继续':'');const duration=settings[mode];
useEffect(()=>localStorage.setItem('settings',JSON.stringify(settings)),[settings]);useEffect(()=>localStorage.setItem('history',JSON.stringify(history)),[history]);useEffect(()=>localStorage.setItem('timer-snapshot',JSON.stringify({mode,left,completedInSet:setCount})),[mode,left,setCount]);
useEffect(()=>{if(!running)return;let finished=false;const tick=()=>{const n=Math.max(0,Math.ceil((deadline-Date.now())/1000));setLeft(n);if(n===0&&!finished){finished=true;finish()}};tick();const id=setInterval(tick,200);return()=>clearInterval(id)},[running,deadline]);const stats=useMemo(()=>todayStats(history),[history]);
function begin(){setDeadline(Date.now()+left*1000);setRunning(true)}function pause(){setLeft(Math.max(0,Math.ceil((deadline-Date.now())/1000)));setRunning(false)}function reset(){setRunning(false);setLeft(duration)}function announce(text:string){setNotice(text);window.desktop?.notify('番茄钟提醒',text).catch(()=>{});if(settings.sound)try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();g.gain.value=settings.volume/100;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.2)}catch{}}
function finish(){setRunning(false);if(mode==='focus'){const next=setCount+1;setHistory(h=>[{phase:'focus',durationSec:duration,completedAt:new Date().toISOString(),completed:true},...h]);const nm:Mode=next%4===0?'long':'short';setSetCount(next%4);setMode(nm);setLeft(settings[nm]);announce(`本轮番茄完成，进入${labels[nm]}`)}else{setMode('focus');setLeft(settings.focus);announce('休息结束，开始专注')}}function manual(){if(running)pause();const nm:Mode=mode==='focus'?(setCount%4===3?'long':'short'):'focus';setMode(nm);setLeft(settings[nm]);setNotice(`已手动结束${labels[mode]}，进入${labels[nm]}`)}function changeDuration(k:Mode,v:string){const n=validDuration(Number(v));if(!n){setNotice('时长必须是 1–86400 秒的数字');return}setSettings(x=>({...x,[k]:n}));if(k===mode&&!running)setLeft(n)}
return <div className={`app ${settings.theme}`}><header><h1>个人番茄钟助手</h1><nav>{[['timer','计时'],['settings','设置'],['stats','统计']].map(([k,v])=><button key={k} aria-pressed={tab===k} onClick={()=>setTab(k)}>{v}</button>)}</nav><button onClick={()=>setSettings(x=>({...x,theme:x.theme==='light'?'dark':'light'}))}>切换主题</button></header>{notice&&<div className="notice" role="status">{notice}</div>}{tab==='timer'&&<main><div className="modes">{(Object.keys(labels)as Mode[]).map(k=><button key={k} aria-pressed={mode===k} onClick={()=>{setRunning(false);setMode(k);setLeft(settings[k])}}>{labels[k]}</button>)}</div><p>{labels[mode]} · {running?'进行中':'已暂停'} · 本组 {setCount}/4</p><div className="time" aria-live="polite">{String(Math.floor(left/60)).padStart(2,'0')}:{String(left%60).padStart(2,'0')}</div><p>今日完成 {stats.count} 个番茄</p><button onClick={running?pause:begin}>{running?'暂停':left<duration?'继续':'开始'}</button><button onClick={reset}>重置</button><button onClick={manual}>手动结束</button></main>}{tab==='settings'&&<section><h2>设置</h2>{(Object.keys(labels)as Mode[]).map(k=><label key={k}>{labels[k]}时长（秒；默认 {k==='focus'?25:k==='short'?5:15} 分钟）<input type="number" min="1" max="86400" value={settings[k]} onChange={e=>changeDuration(k,e.target.value)}/></label>)}<label>提醒音量 {settings.volume}%<input type="range" min="0" max="100" value={settings.volume} onChange={e=>setSettings(x=>({...x,volume:+e.target.value}))}/></label><label><input type="checkbox" checked={settings.sound} onChange={e=>setSettings(x=>({...x,sound:e.target.checked}))}/> 开启音效</label></section>}{tab==='stats'&&<section><h2>统计</h2><p>今日完成番茄：{stats.count}</p><p>今日专注时长：{Math.floor(stats.seconds/60)} 分钟</p><p>历史记录：{history.length} 条</p><button onClick={()=>{if(window.confirm('确定清空全部历史记录？')){setHistory([]);setNotice('历史记录已清空')}}}>清空历史记录</button><ul>{history.slice(0,10).map((x,i)=><li key={i}>{labels[x.phase]} · {new Date(x.completedAt).toLocaleString()}</li>)}</ul></section>}</div>};createRoot(document.getElementById('root')!).render(<App/>);

